### ISSUE TITLE
Crazy font display (upon keywords?)

### ISSUE THREAD

**Issue by stebiger** [coopermaruyama/apathy-theme#15]
Hey,

back here with another bug for your syntax theme - at least I can only reproduce it with apathy and not any of the other default atom themes.

Some keywords may be displayed really crazy - is this intended behaviour or what causes this?

![image](https://cloud.githubusercontent.com/assets/8200750/8696544/655b9d0c-2aed-11e5-8dc9-b02ded400408.png)

**Comment by stebiger** [comment]
Addition: This is only for Inconsulata font - the Source Code Pro Font works as expected - so maybe this is a special case of the font / intended behaviour of the font?

**Comment by czxtm** [comment]
Oh wow, that indeed is crazy haha. It sort of looks like the "crazy" looking text is the bold font, correct? If so, then maybe it's an issue with the font itself. The 'regular' Inconsolata uses OTF and bold uses TTF since the original creator never made a bold (as far as my memory serves). If it's just the bold font, try replacing the one in the theme at `styles/fonts` and see if it fixes it.

**Comment by czxtm** [comment]
Closing this as it's old - let me know if you have any updates and feel free to reopen if it's still happening!
