### ISSUE TITLE
Wrap guide

### ISSUE THREAD

**Issue by ghost** [coopermaruyama/apathy-theme#23]
Wrap guide doesn't show up. I am using this syntax theme with Atom Material UI. I tried reloading & rebooting, but to no avail.

PS. Is it fully supporting .jsx ?

**Comment by czxtm** [comment]
Unfortunately I removed it recently, as it was causing too many other bugs and was not worth the cost in terms of how much I had to hack atom to get it to work. 

The guide itself was not the problem, but the option to add padding meant that all the text needed to be shifted to the right. This puts the text out-of-sync with atom's cursor position, and getting those in sync meant adding in code that constantly had to run (since cursors are always pretty active). Without the padding, the left wrap guide is pretty worthless, so I removed both.

If you really want it back, you can run `apm dev apathy-theme` to grab a dev version, and roll it back to this commit id: `40df5b18004b75114971afe17c7167c2d5fb0d3f`.

As for full jsx support - no. But jsx inherits from the JS styles, so it still looks decent. I'll add some jsx styles soon, though. In the meantime #24 will serve as a reminder.
