### ISSUE TITLE
Weird cursor position

### ISSUE THREAD

**Issue by leighkendell** [coopermaruyama/apathy-theme#4]
I'm seeing an issue with some files where the cursor will be a few pixels out from where it should be. In the screenshot attached the cursor is actually immediately after that bracket, not a couple of spaces to the right as it appears.

![image](https://cloud.githubusercontent.com/assets/765486/7517872/1e572a2a-f50a-11e4-9dfd-489f8634b4f8.png)

One thing I did try was changing the font size after reading this thread: https://discuss.atom.io/t/weird-bug-with-spacing-with-certain-fonts/2565/5 and it seems to be behaving normally at 15px but any other font size the cursor position gets messed up.

**Comment by leighkendell** [comment]
Actually scrap the font size thing, when I relaunched Atom it was broken again.

**Comment by czxtm** [comment]
Yeah, I noticed that too, it will happen every single time you restart atom for files that were already open but goes away if you close/reopen it. I assumed it wasn't specific to my theme since it happened even when it was only utilizing CSS but I just tested with some other themes and it does seem like it only happens on this theme, so thanks for reporting this.

I'll fix this ASAP, I could see this getting really annoying if you have un-saved changes.

**Comment by czxtm** [comment]
Alright I've added a fix in the newest version, although a bit hacky:  The theme will now force a re-calculation of the cursor's offset upon reloading/reopening, but since all the atom event callbacks that are available don't wait until the cursor has been rendered, I've instead bound this to occur after the first "cursorMoved" event. So the cursor will be positioned wrong initially, but as soon as you click inside the editor for the first time (or click an arrow key) the cursor should fix itself. Please give it a shot and let me know if it works.

This bug was caused by the theme using antialiased font smoothing which has the side effect of rendering characters at various widths; Whereas without antialiasing, all characters render at the same width. I think atom simply figures these out and adds them up to determine cursor position (an obviously flawed approach that the Atom team has [recognized as an issue](https://github.com/atom/atom/issues/6055) ), but this is not persisted through some events such as reloading. 

Also I just realized you mentioned something about the font size causing the cursor to get messed up? Is this still happening? That one is new to me.,

**Comment by leighkendell** [comment]
Thanks! Yeah I think maybe the change of font size just triggered the refresh like an open/close does. Looks to be working as normal now :+1:

**Comment by czxtm** [comment]
Glad to help - I also had this issue, so thanks for reporting it! :ok_hand:
